"""Create your own adventure experience - Guessing a number."""

__author__ = "730463543"

import random
points: int = 0
player: str = ""
CELEBRATION_EMOJI: str = "\U0001F389"
WAVING_EMOJI: str = "\U0001F44B"


def greet() -> None:
    """Greeting function."""
    global player
    print(f"Hello{WAVING_EMOJI} new player and welcome to the number guessing game! Today you will have the chance to guess a number and how close that number is to the random number generated by the computer is how many points you get. The lower the point total the better!")
    player = input("If you don't mind me asking, what is your name? ")


def safe() -> None:
    """Safe version of the guessing game."""
    global points
    global player
    print(f"{player}, welcome to the low risk version of this number guessing game! Like I said before, you will guess a number between the bounds given and the difference between your number and the random number generated will be added to your score. The lower your score after 5 rounds, the better!")
    round_idx: int = 1
    playing: bool = True
    rand_number: int = 0
    player_guess: int = 0
    guess_diff: int = 0
    while playing is True:
        while round_idx <= 5:
            rand_number = random.randint(0, 20)
            player_guess = int(input(f"Round {round_idx}/5: The random number will be within the bounds of 0 and 20. What is your guess? "))
            guess_diff = abs(rand_number - player_guess)
            points = points + guess_diff
            print(f"The random number was {rand_number}! That means the difference between your guess and the random number was {guess_diff}. After round {round_idx}, your score is {points}.")
            round_idx += 1
        print(f"Your score after 5 rounds of the low risk version was {points}!")
        playing = False


def risky(guess: int) -> int:
    """Risky version of the guessing game."""
    points: int = 0
    rand_number: int = random.randint(0, 20)
    diff: int = abs(guess - rand_number)
    if diff > 5:
        print(f"The random number was {rand_number} and your guess was more than 5 off. That means that you gained {diff + diff} points in this round.")
        points = diff * 2
        return points
    if diff == 5:
        print(f"Your guess was off by {diff}! This means you will have 1 point subtracted from your score!")
        points = -1
        return points
    if diff == 4:
        print(f"Your guess was off by {diff}! This means you will have 2 points subtracted from your score!")
        points = -2
        return points
    if diff == 3:
        print(f"Your guess was off by {diff}! This means you will have 3 points subtracted from your score!")
        points = -3
        return points
    if diff == 2:
        print(f"Your guess was off by {diff}! This means you will have 4 points subtracted from your score!")
        points = -4
        return points
    if diff == 1:
        print(f"Your guess was off by {diff}! This means you will have 5 points subtracted from your score!")
        points = -5
        return points
    if diff == 0:
        print(f"{CELEBRATION_EMOJI}Your guess was off by {diff}! This means you will have 10 points subtracted from your score!{CELEBRATION_EMOJI}")
        points = -10
        return points
    return points


def main() -> None:
    """Main funtion in which everything is run through."""
    greet()
    print(f"Alrighty {player}, you have 3 options. Your first option is to play the low risk version, where the difference between your number and the random number is just simply added to your score and you see how many points you have after 5 rounds. The second option is to play the risky game. The difference in this game is that if you are within a certain amount of the random number, you will get points deducted from your total, but if you are too far away the penalty of points is even bigger! The third option is to take your current score as your final score and end your experience with the game!")
    playing: bool = True
    choice: int = int(input("If you want to play the low risk/easy game, enter the number 1. If you want to play the high risk/hard game, enter the number 2. If you want to exit, enter any other number! "))
    while playing is True:
        if choice == 1:
            safe()
        if choice == 2:
            global points
            round_idx: int = 1
            print(f"{player}, welcome to the high risk version of this guessing game! In this version, if your guess is within 5 of the random number, you will get points off of your score. If it is not, you will get 1.5 times the difference between your guess and the number added to your score. The lower your score after 5 rounds, the better!")
            print("Point off scale: 5 away: -1 point, 4 away: -2 points, 3 away: -3 points, 2 away: -4 points, 1 away: -5 points, 0 away: -10 points")
            while round_idx <= 5:
                player_guess: int = int(input(f"Round {round_idx}/5: The random number will be within the bounds of 0 and 20. What is your guess? "))
                points = points + int(risky(player_guess))
                print(f"After round {round_idx}/5, your point total is {points}!")
                round_idx += 1
            print(f"After {round_idx} rounds of the risky version, your point total was {points}!")
        if choice != 1 or 2:
            print(f"{player}, thank you for playing my number guessing game! Your last attempt yielded a point total of {points}, feel free to come by again soon and get even lower!")
        decision: int = int(input(f"Your last attempt yielded {points} points, but you can keep playing to get lower! If you want to play the easy version, enter the number 1. If you want to play the hard version, enter the number 2. If you want to stop playing, type in any other number! "))
        if decision == 1 or 2:
            playing = True
            choice = decision
        else:
            playing = False


if __name__ == "__main__":
    main()